sudo: required
services:
   - docker

before_install:
  - docker build -t tsveti359/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tsveti359/react-test npm test -- --coverage

after_success:
  - docker build -t tsveti359/multi-client ./client
  - docker build -t tsveti359/multi-nginx ./nginx
  - docker build -t tsveti359/multi-server ./server
  - docker build -t tsveti359/multi-worker ./worker
  # Log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push tsveti359/multi-client
  - docker push tsveti359/multi-nginx
  - docker push tsveti359/multi-server
  - docker push tsveti359/multi-worker